name: Test with pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build the docker-compose stack
      run: docker-compose up -d

    - name: Sleep
      uses: jakejarvis/wait-action@master
      with:
      time: '120s'

    - name: Check running containers
      run: docker ps -a

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest






